#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import json

from core import atena_terminal_assistant as ta


def test_materialize_self_generated_assets_creates_module_skill_plugin(monkeypatch, tmp_path):
    monkeypatch.setattr(ta, "ROOT", tmp_path)
    payload = {
        "status": "ok",
        "sources": [
            {
                "source": "github",
                "ok": True,
                "details": {"top_repos": [{"full_name": "org/cool-agent-framework"}]},
            }
        ],
    }
    created = ta.materialize_self_generated_assets("agentic systems", payload)
    assert len(created) == 1

    manifest_path = tmp_path / "atena_evolution" / "self_generated_assets.json"
    assert manifest_path.exists()
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    assert manifest["assets"]

    module_path = tmp_path / created[0]["module_path"]
    assert module_path.exists()
    assert "Auto-generated by ATENA" in module_path.read_text(encoding="utf-8")


def test_materialize_self_generated_assets_deduplicates(monkeypatch, tmp_path):
    monkeypatch.setattr(ta, "ROOT", tmp_path)
    payload = {
        "status": "ok",
        "sources": [
            {"source": "github", "ok": True, "details": {"top_repos": [{"full_name": "org/repo-x"}]}},
        ],
    }
    first = ta.materialize_self_generated_assets("topic", payload)
    second = ta.materialize_self_generated_assets("topic", payload)
    assert len(first) == 1
    assert second == []
